### PR TITLE
Fixed Permissions to work with android 10

### PR DESCRIPTION
**Pull request by ZeBrody**
I added the missing ACCESS_FINE_LOCATION permission, because it won't work on Android 10 without it. Also updated the compileSdkVersion to 29.

### CODE REVIEW

**Comment by abreudiego94** [comment]
Merge please

**Comment by carlosalito** [comment]
Merge please!

**Comment by vishnuagbly** [comment]
looks like this project has been abandoned, if anyone interested we are planning to create a new package forked from this one. Read comment on #122

**Comment by zeevgrim** [comment]
Merge please!

**Comment by nightscape** [comment]
Resolved via https://github.com/edufolly/flutter_bluetooth_serial/pull/137 (which is basically this PR rebased onto master).
Thank you @ZeBrody for the contribution!

**Pull request closed without merging**
