### PR TITLE
Bonding

### PR DESCRIPTION
**Pull request by PsychoXIVI**
Adding bonding functionality. Requested by @FWeissenb.

Features:
+ outgoing pairing request,
+ pairing automation (by pass-key confirmation and by preselected pin),
+ able to detect canceling (`false`) instead of throwing it as error.

To do:
- listening incoming pairing request (`setPairingRequestHandler`) **[work in progress]**
- make user able to check pass-key while pairing automation (instead of just `confirmPasskey` flag),
- remove possibility of memory leak.

Needs further consideration:
* confirmation of pairing key needs permission unavailable for 3rd party application (but should stay in the code :F),
* ...

### CODE REVIEW

**Comment by PsychoXIVI** [comment]
I am stuck... https://stackoverflow.com/questions/56726479/does-broadcastreceiver-always-abort-action-pairing-request

**Comment by FWeissenb** [comment]
@PsychoXIVI  
Works for me. 

I used the example to discover and bond device and send some commands.
Some remarks: in DiscoveryPage you get errors if the discovered device doesn't have a device name, something like  `title: Text(device.name ?? ""),` in BluetoothDeviceListEntry.dart would be useful. 
It would also be useful if you insert a text field to insert the pin code, atm it's hardcoded.
And the last comment: I tried to use the chat page to talk with my device and wondered why 
I don't get a response. The reason was the attached \r\n and the "parse line ending" in the read callback.. So making this optional would be nice.

**Comment by PsychoXIVI** [comment]
For now I will left this PR here, since there I still have a problem with `BroadcastReceiver`. There is WIP commit, which will be overwritten by force push when solution is found. 

The issues for example code would be addressed after resolving the main problem.

**Comment by PsychoXIVI** [comment]
I found satisfying solution 🎉 

For now: 

Features:
+ Starting pairing process (`bondDeviceAtAddress`),
  * Detectable failure and success,
  * Automation for single pairing (utilizes pairing request handler, so can be used only if there is no other handler set - of course the handler could also handle this one too),
  * Starting pairing on long press on discovered devices list for example,
+ Handling pairing requests (`setPairingRequestHandler`),
  * Multiple variants available (pin, passkey-confirm and consent tested),
  * Automation possible (returning pin string or confirm boolean from handler),
  * Switchable auto-pairing with `1234` pin for example,

To do:
- detectable cancelling by user of (outgoing) requests,
- memory leak seems still to be the thing...

**Comment by PsychoXIVI** [comment]
For now only it would be limited up to one bonding/pairing process ongoing at the same time. I were testing it like a half an hour, and none of two devices I tested were bonded in the result of simultaneous pairing processes.

**Comment by PsychoXIVI** [comment]
The pull request seems to be ready - it will be merged in 3 days if no further changes incoming.

There is few elements on To-Do list left:
1) Detectable cancelling by user of (outgoing) requests - but it would not be addressed by this PR. There is two problems: first - cancel action is not fired to the app receiver (at least in my tests), and second - the string for cancel action is hidden in API.
2) `Symbol not found` problem - missing/hidden constants in API, even if still occurring. For example, my Raspberry Pi can use `PAIRING_VARIANT_CONSENT` (underlying value: `3` integer) for instant, simple (and insecure) pairing.
3) Passing errors from pairing handling result - it is not so critical for now, but yeah, it would be nice to have.

**Pull request merged**
