### PR TITLE
updated to AndroidX and added some TODOS

### PR DESCRIPTION
**Pull request by BugsBunnyBR**

### CODE REVIEW

**Comment by PsychoXIVI** [comment]
I think whole library is targeted for API 18 at least.

**Comment by BugsBunnyBR** [comment]
@PsychoXIVI , it still will break in API 18.

**Comment by BugsBunnyBR** [comment]
@PsychoXIVI , yeah, the main goal of this PR is to update to AndroidX version.

**Comment by nightscape** [comment]
Resolved via https://github.com/edufolly/flutter_bluetooth_serial/pull/136

**Pull request closed without merging**
